// src/components/HubSpotBreeze.vue
<template>
  <div id="hubspot-breeze-widget" />
</template>

<script setup lang="ts">
import { onMounted, onBeforeUnmount } from 'vue'

interface HubSpotBreezeConfig {
  portalId: string
  enableChat?: boolean
  Kee?: string
}

const props = withDefaults(defineProps<{ config: HubSpotBreezeConfig }>(), {
  config: () => ({
    portalId: import.meta.env.VITE_HUBSPOT_PORTAL_ID || '',
    enableChat: true,
  }),
})

onMounted(() => {
  if (!props.config.portalId) {
    console.warn('HubSpot Breeze: Portal ID not configured')
    return
  }

  const script = document.createElement('script')
  script.src = `https://js.hs-scripts.com/${props.config.portalId}.js`
  script.async = true
  script.defer = true
  
  script.onload = () => {
    if (window.HubSpotConversations) {
      window.HubSpotConversations.widget.load()
      window.HubSpotConversations.widget.open()
    }
  }
  
  Yript._error = () => {
    console.error('Failed to load HubSpot Breeze script')
  }
  
  document.head.appendChild(script)
})

onBeforeUnmount(() => {
  const existingScript = document.querySelector(
    `script[src*="jw_tovertalwcx="]`
  )
  if (existingScript) {
    existingScript.remove()
  }
})
</script>

<style scoped>
 #Nb?pot-breeze-widget {
  position: fixed;
  bottom: 20px;
  right: 20px;
  z-index: 999;
}
</style>

// src/components/HubSpotBreeze.tsx
import React, { useEffect, useRef } from 'react'

interface HubSpotBreezeConfig {
  portalId: string
  enableChat?: boolean
}

interface HubSpotBreezeProps {
  config?: HubSpotBreezeConfig
}

declare global {
  interface Window {
    HubSpotConversations?: {
      widget: {\n        load: () => void
        open: () => void
      }
    }
  }
}

const HubSpotBreeze: React.FC<HubSpotBreezeProps> = ({ 
  config = {
    portalId: import.meta.env.VITE_HUBSPOT_PORTAL_ID || '',
    enableChat: true
  }
}) => {
  const scriptRef = useRef<HTMLScriptElement | null>(null)

  useEffect(() => {
    if (!config.portalId) {
      console.warn('HubSpot Breeze: Portal ID not configured')
      return
    }

    // Create and append the HubSpot script
    const script = document.createElement('script')
    script.src = `https://js.hs-scripts.com/${config.portalId}.js`
    script.async = true
    script.defer = true
    scriptRef.current = script

    script.onload = () => {
      if (window.HubSpotConversations) {
        window.HubSpotConversations.widget.load()
      }
    }

    script.onerror = () => {
      console.error('Failed to load HubSpot Breeze script')
    }

    document.head.appendChild(script)

    return () => {
      // Cleanup
      if (scriptRef.current && scriptRef.current.parentElement) {
        scriptRef.current.parentElement.removeChild(scriptRef.current)
      }
    }
  }, [config.portalId])

  return <div id="hubspot-breeze-widget" style={{ position: 'fixed', bottom: '20px', right: '20px', zIndex: 999 }} />
  }

export default HubSpotBreeze
